---
# pre task
- name: Executing defined pre tasks.
  ansible.builtin.import_tasks: pre_tasks.yml

# Use add-apt-repository for Launchpad PPAs
- name: "Add Launchpad PPA for {{ apt_package.apt_package_name }}"
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:{{ apt_package.launchpad_ppa }}"
    state: present
    update_cache: true
  when:
    - apt_package.launchpad_ppa is defined
    - apt_package.launchpad_ppa | length > 0

# main tasks for manual repository configuration
- name: "Get key from ubuntu key server for {{ apt_package.apt_package_name }}"
  ansible.builtin.shell: |
    gpg --no-default-keyring --keyring {{ apt_key_temp_path_template }}.gpg --keyserver keyserver.ubuntu.com --recv-keys {{ apt_package.apt_key_server_key }}
    gpg --no-default-keyring --keyring {{ apt_key_temp_path_template }}.gpg --export > {{ apt_key_temp_path_template }}_final.gpg
    rm {{ apt_key_temp_path_template }}.gpg
  changed_when: true
  when:
    - "'apt_key_server_key' in apt_package"
    - not local_processed_key_check.stat.exists
    - apt_package.launchpad_ppa is not defined

- name: "Copy key to final location"
  become: true
  ansible.builtin.copy:
    src: "{{ apt_key_temp_path_template }}_final.gpg"
    dest: "{{ local_processed_key_path }}"
    remote_src: true
    mode: '0644'
  when:
    - "'apt_key_server_key' in apt_package"
    - not local_processed_key_check.stat.exists
    - apt_package.launchpad_ppa is not defined

- name: "Get raw key from url for {{ apt_package.apt_package_name }}"
  ansible.builtin.get_url:
    url: "{{ apt_package.apt_key_url }}"
    dest: "{{ local_raw_key_path }}"
    mode: '0644'
  when:
    - not local_processed_key_check.stat.exists
    - "'apt_key_server_key' not in apt_package"
    - apt_package.launchpad_ppa is not defined

- name: "Dearmor key for {{ apt_package.apt_package_name }}"
  become: true
  ansible.builtin.shell:
    cmd: "set -o pipefail && cat {{ local_raw_key_path }} | gpg --dearmor > {{ local_processed_key_path }}"
    executable: /bin/bash
  changed_when: true
  when:
    - not local_processed_key_check.stat.exists
    - "'apt_key_server_key' not in apt_package"
    - apt_package.launchpad_ppa is not defined

- name: "Add Repository using modern .sources format for {{ apt_package.apt_package_name }}"
  become: true
  ansible.builtin.template:
    src: apt_source.j2
    dest: "/etc/apt/sources.list.d/{{ apt_package.apt_package_name }}.sources"
    mode: '0644'
  notify: Update apt cache
  when:
    - apt_package.launchpad_ppa is not defined

- name: "Install packages for {{ apt_package.apt_package_name }}"
  become: true
  ansible.builtin.apt:
    name: "{{ apt_package.apt_install_list }}"
    update_cache: true

# post task
- name: Executing defined post tasks.
  ansible.builtin.import_tasks: post_tasks.yml
