---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-ppa-test
    image: ubuntu:24.04
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu-ppa-test:
        ansible_user: root
        local_gpg_keyrings_path: /etc/apt/keyrings
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy