---
- name: Prepare
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - gnupg
          - gpg
          - curl
          - ca-certificates
          - lsb-release
        state: present